### ISSUE TITLE
Add Quantus to list of XAI evaluation libraries

### ISSUE THREAD

**Issue by annahedstroem** [jphall663/awesome-machine-learning-interpretability#210]
Hey! Thanks for compiling this great list of XAI work.

Consider adding [Quantus](https://github.com/understandable-machine-intelligence-lab/Quantus) to the list of evaluation packages (published in JMLR (2023), [paper](https://jmlr.org/papers/v24/22-0142.html)). Thanks.

**Comment by jphall663** [comment]
@annahedstroem looks great! @datherton09 please add!

**Comment by datherton09** [comment]
Done! Thank you! :)
