### ISSUE TITLE
Where to include articles/materials related debugging Deep Neural Nets?

### ISSUE THREAD

**Issue by sayakpaul** [jphall663/awesome-machine-learning-interpretability#24]
Hi @jphall663. The following articles deal with the debugging prospects of Deep Neural Networks:

- [Visualizing and debugging deep convolutional networks](https://rohitghosh.github.io/)
- [Troubleshooting Deep Neural Networks](http://josh-tobin.com/assets/pdf/troubleshooting-deep-neural-networks-01-19.pdf)
- [Things I wish we had known before we started our first Machine Learning project](https://medium.com/infinity-aka-aseem/things-we-wish-we-had-known-before-we-started-our-first-machine-learning-project-336d1d6f2184)
- [Practical Advice for Building Deep Neural Networks](https://pcc.cs.byu.edu/2017/10/02/practical-advice-for-building-deep-neural-networks/)
- [Top 6 errors novice machine learning engineers make](https://medium.com/ai%C2%B3-theory-practice-business/top-6-errors-novice-machine-learning-engineers-make-e82273d394db)
- [A Recipe for Training Neural Networks](http://karpathy.github.io/2019/04/25/recipe/)
- [Training Neural Nets: a Hacker’s Perspective](https://blog.floydhub.com/training-neural-nets-a-hackers-perspective/)

In which section can we place these?

**Comment by jphall663** [comment]
@sayakpaul Are they just articles? I don't want to start collecting articles. There's just too many and the quality can be very poor ... see "Toward Data Science" - LOL (jk ... kind of).

If these include comprehensive code examples, please send a PR with them added into the `Comprehensive Software Examples and Tutorials` section.

In general, I'm getting very interested in model debugging (eg, https://medium.com/@jphall_22520/strategies-for-model-debugging-aa822f1097ce) so PLEASE keep sending info on this topic. 

Without looking very hard, this one seems good for comprehensive software examples: https://blog.floydhub.com/training-neural-nets-a-hackers-perspective/ and this one seems legit enough for `Other Interpretability and Fairness Resources and Lists`: http://josh-tobin.com/assets/pdf/troubleshooting-deep-neural-networks-01-19.pdf.

**Comment by sayakpaul** [comment]
@jphall663 understood. To your point, I would just add Andrej Karpathy's article [A Recipe for Training Neural Nets](http://karpathy.github.io/2019/04/25/recipe/). I will go ahead and close this issue and will submit a PR.

I will also keep looking for good stuff around model debugging and will communicate them to you :)
