### ISSUE TITLE
Items for new categories

### ISSUE THREAD

**Issue by jphall663** [jphall663/awesome-machine-learning-interpretability#283]
Red-teaming: 
- ACL 2024 Tutorial: Vulnerabilities of Large Language Models to Adversarial Attacks
- CDAO frameworks, guidance, and best practices for AI test & evaluation
- ChatGPT_system_prompt
- DAIR prompting guide, risks and misuses
- Extracting Training Data from ChatGPT
- Frontier Model Forum: What is Red Teaming?
- Identifying and Eliminating CSAM in Generative ML Training Data and Models
- Microsoft: Microsoft AI Red Team building future of safer AI
- OpenAI Red Teaming Network
- Red Teaming of Advanced Information Assurance Concepts
- Red Teaming Language Models to Reduce Harms: Methods, Scaling Behaviors, and Lessons Learned

Cheatsheets and infographics: 
- Machine Learning Attack_Cheat_Sheet
- Different types of AI:  https://fpf.org/wp-content/uploads/2021/01/FPF_AIEcosystem_illo_03.pdf (new)

**Comment by datherton09** [comment]
benchmarks:
- https://wavesbench.github.io/
- https://github.com/huggingface/evaluate
- https://github.com/AI-secure/DecodingTrust
- https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vQObeTxvXtOs--zd98qG2xBHHuTTJOyNISBJPthZFr3at2LCrs3rcv73d4of1A78JV2eLuxECFXJY43/pubhtml
- https://safetyprompts.com/

python software: 
- https://github.com/lilacai/lilac

official guidance:
- https://www.ohchr.org/sites/default/files/documents/issues/business/b-tech/taxonomy-GenAI-Human-Rights-Harms.pdf

community resources: 
- https://www.hackerone.com/vulnerability-and-security-testing-blog
- https://www.synack.com/wp-content/uploads/2022/09/Crowdsourced-Security-Landscape-Government.pdf
- CSET stuff (just double check we reference somehow):
-- https://cset.georgetown.edu/article/translating-ai-risk-management-into-practice/
-- https://cset.georgetown.edu/publication/repurposing-the-wheel/
-- https://cset.georgetown.edu/publication/adding-structure-to-ai-harm/
-- https://cset.georgetown.edu/article/understanding-ai-harms-an-overview/
-- https://cset.georgetown.edu/publication/ai-incident-collection-an-observational-study-of-the-great-ai-experiment/
- https://www.scsp.ai/wp-content/uploads/2023/11/SCSP_JHU-HCAI-Framework-Nov-6.pdf
- https://openai.com/research/building-an-early-warning-system-for-llm-aided-biological-threat-creation
- https://c2pa.org/
- https://aiverifyfoundation.sg/downloads/Cataloguing_LLM_Evaluations.pdf
- https://partnershiponai.org/modeldeployment/
- https://cdn.openai.com/openai-preparedness-framework-beta.pdf

red-teaming section:
- https://www.hackerone.com/thought-leadership/ai-safety-red-teaming
- https://cset.georgetown.edu/article/what-does-ai-red-teaming-actually-mean/
