### ISSUE TITLE
Critique section

### ISSUE THREAD

**Issue by datherton09** [jphall663/awesome-machine-learning-interpretability#300]
https://assets.cureus.com/uploads/editorial/pdf/138667/20230219-28928-6kcyip.pdf
https://arxiv.org/pdf/2304.15004.pdf
https://arxiv.org/pdf/2312.16337.pdf
https://arxiv.org/pdf/2311.00871.pdf
https://arxiv.org/pdf/2311.17035.pdf
https://stacks.stanford.edu/file/druid:kh752sm9123/ml_training_data_csam_report-2023-12-23.pdf
https://faculty.washington.edu/aylin/publications.html
https://arxiv.org/pdf/2312.11671.pdf
https://arxiv.org/abs/2308.08708
https://www.wired.com/story/get-ready-for-the-great-ai-disappointment/
https://arstechnica.com/ai/2024/01/lazy-use-of-ai-leads-to-amazon-products-called-i-cannot-fulfill-that-request/
https://www.itpro.com/business/leadership/most-ceos-arent-buying-the-hype-on-generative-ai-benefits
https://www.rollingstone.com/culture/culture-features/ai-companies-advocates-cult-1234954528/
https://www.consumerfinance.gov/data-research/research-reports/chatbots-in-consumer-finance/chatbots-in-consumer-finance/
https://arxiv.org/abs/2310.02446v1
https://arxiv.org/pdf/2402.11753.pdf
https://arxiv.org/pdf/2402.03927.pdf
https://rdcu.be/dAw4I
https://www.unesco.org/en/articles/generative-ai-unesco-study-reveals-alarming-evidence-regressive-gender-stereotypes
https://www.newscientist.com/article/2421067-ai-chatbots-use-racist-stereotypes-even-after-anti-racism-training/
https://www.barrons.com/news/ai-tools-still-permitting-political-disinfo-creation-ngo-warns-ac791521
https://www.dtu.dk/english/news/all-news/researchers-surprised-by-gender-stereotypes-in-chatgpt?id=7e5936d1-dfce-485b-8a90-78f7c757177d

**Comment by jphall663** [comment]
Machine Learning: The High Interest Credit Card of Technical Debt: https://research.google/pubs/machine-learning-the-high-interest-credit-card-of-technical-debt/

WINNER’S CURSE?
ON PACE, PROGRESS, AND EMPIRICAL RIGOR: https://openreview.net/pdf?id=rJWF0Fywf

The Data Scientific Method vs. The Scientific Method: https://odsc.com/blog/the-data-scientific-method-vs-the-scientific-method/

AI Snake Oil: https://www.aisnakeoil.com/ (blog/substack)

The Fallacy of AI Functionality: https://dl.acm.org/doi/pdf/10.1145/3531146.3533158

Data and its (dis)contents: A survey of dataset development and use in machine learning research: https://www.cell.com/patterns/pdf/S2666-3899(21)00184-7.pdf

Against predictive optimization: https://predictive-optimization.cs.princeton.edu/

Measuring the predictability of life outcomes with a scientific mass collaboration: https://www.pnas.org/doi/10.1073/pnas.1915006117

On the Dangers of Stochastic Parrots: Can Language Models Be Too Big?: https://dl.acm.org/doi/pdf/10.1145/3442188.3445922

AI Is a Lot of Work: https://nymag.com/intelligencer/article/ai-artificial-intelligence-humans-technology-business-factory.html

Insanely Complicated, Hopelessly Inadequate: https://www.lrb.co.uk/the-paper/v43/n02/paul-taylor/insanely-complicated-hopelessly-inadequate

**Comment by datherton09** [comment]
https://www.theatlantic.com/ideas/archive/2024/03/artificial-intelligence-google-gemini-mind-control/677683/

**Comment by datherton09** [comment]
"Critiques of Generative AI" section created. All links above added. In future, we can use this thread to quickly add candidates for submission to this section of the repository.

**Comment by datherton09** [comment]
https://arxiv.org/pdf/2305.17493v2.pdf
