### ISSUE TITLE
show github stars?

### ISSUE THREAD

**Issue by ghost** [jphall663/awesome-machine-learning-interpretability#47]
super awesome list, have you considered adding github stars for each repo like was done here?:
https://github.com/wangyongjie-ntu/Awesome-explainable-AI

Makes it especially useful for folks who are looking for a well-maintained solution.

**Comment by jphall663** [comment]
This is a good idea. Thanks.

**Comment by datherton09** [comment]
![](https://img.shields.io/github/stars/username/repo-name?style=social)
